#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : flac
Version  : 1.3.2
Release  : 11
URL      : http://downloads.xiph.org/releases/flac/flac-1.3.2.tar.xz
Source0  : http://downloads.xiph.org/releases/flac/flac-1.3.2.tar.xz
Summary  : Free Lossless Audio Codec Library (C++ API)
Group    : Development/Tools
License  : BSD-3-Clause GFDL-1.2 GPL-2.0 LGPL-2.1
Requires: flac-bin
Requires: flac-lib
Requires: flac-doc
BuildRequires : doxygen
BuildRequires : gcc-dev32
BuildRequires : gcc-libgcc32
BuildRequires : gcc-libstdc++32
BuildRequires : glibc-dev32
BuildRequires : glibc-libc32
BuildRequires : libogg-dev
BuildRequires : libogg-dev32
BuildRequires : nasm-bin

%description
/* FLAC - Free Lossless Audio Codec
*
* This file is part the FLAC project.  FLAC is comprised of several
* components distributed under different licenses.  The codec libraries
* are distributed under Xiph.Org's BSD-like license (see the file
* COPYING.Xiph in this distribution).  All other programs, libraries, and
* plugins are distributed under the LGPL or GPL (see COPYING.LGPL and
* COPYING.GPL).  The documentation is distributed under the Gnu FDL (see
* COPYING.FDL).  Each file in the FLAC distribution contains at the top the
* terms under which it may be distributed.
*
* Since this particular file is relevant to all components of FLAC,
* it may be distributed under the Xiph.Org license, which is the least
* restrictive of those mentioned above.  See the file COPYING.Xiph in this
* distribution.
*/

%package bin
Summary: bin components for the flac package.
Group: Binaries

%description bin
bin components for the flac package.


%package dev
Summary: dev components for the flac package.
Group: Development
Requires: flac-lib
Requires: flac-bin
Provides: flac-devel

%description dev
dev components for the flac package.


%package dev32
Summary: dev32 components for the flac package.
Group: Default
Requires: flac-lib32
Requires: flac-bin
Requires: flac-dev

%description dev32
dev32 components for the flac package.


%package doc
Summary: doc components for the flac package.
Group: Documentation

%description doc
doc components for the flac package.


%package lib
Summary: lib components for the flac package.
Group: Libraries

%description lib
lib components for the flac package.


%package lib32
Summary: lib32 components for the flac package.
Group: Default

%description lib32
lib32 components for the flac package.


%prep
%setup -q -n flac-1.3.2
pushd ..
cp -a flac-1.3.2 build32
popd

%build
export LANG=C
export SOURCE_DATE_EPOCH=1483293488
export CFLAGS="$CFLAGS -O3 -falign-functions=32 -ffast-math -fno-semantic-interposition -ftree-loop-vectorize "
export FCFLAGS="$CFLAGS -O3 -falign-functions=32 -ffast-math -fno-semantic-interposition -ftree-loop-vectorize "
export FFLAGS="$CFLAGS -O3 -falign-functions=32 -ffast-math -fno-semantic-interposition -ftree-loop-vectorize "
export CXXFLAGS="$CXXFLAGS -O3 -falign-functions=32 -ffast-math -fno-semantic-interposition -ftree-loop-vectorize "
%configure --disable-static
make V=1  %{?_smp_mflags}

pushd ../build32/
export PKG_CONFIG_PATH="/usr/lib32/pkgconfig"
export CFLAGS="$CFLAGS -m32"
export CXXFLAGS="$CXXFLAGS -m32"
export LDFLAGS="$LDFLAGS -m32"
%configure --disable-static    --libdir=/usr/lib32 --build=i686-generic-linux-gnu --host=i686-generic-linux-gnu --target=i686-clr-linux-gnu
make V=1  %{?_smp_mflags}
popd
%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost
make VERBOSE=1 V=1 %{?_smp_mflags} check || :

%install
rm -rf %{buildroot}
pushd ../build32/
%make_install32
if [ -d  %{buildroot}/usr/lib32/pkgconfig ]
then
pushd %{buildroot}/usr/lib32/pkgconfig
for i in *.pc ; do ln -s $i 32$i ; done
popd
fi
popd
%make_install

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/flac
/usr/bin/metaflac

%files dev
%defattr(-,root,root,-)
/usr/include/FLAC++/all.h
/usr/include/FLAC++/decoder.h
/usr/include/FLAC++/encoder.h
/usr/include/FLAC++/export.h
/usr/include/FLAC++/metadata.h
/usr/include/FLAC/all.h
/usr/include/FLAC/assert.h
/usr/include/FLAC/callback.h
/usr/include/FLAC/export.h
/usr/include/FLAC/format.h
/usr/include/FLAC/metadata.h
/usr/include/FLAC/ordinals.h
/usr/include/FLAC/stream_decoder.h
/usr/include/FLAC/stream_encoder.h
/usr/lib64/libFLAC++.so
/usr/lib64/libFLAC.so
/usr/lib64/pkgconfig/flac++.pc
/usr/lib64/pkgconfig/flac.pc
/usr/share/aclocal/*.m4

%files dev32
%defattr(-,root,root,-)
/usr/lib32/libFLAC++.so
/usr/lib32/libFLAC.so
/usr/lib32/pkgconfig/32flac++.pc
/usr/lib32/pkgconfig/32flac.pc
/usr/lib32/pkgconfig/flac++.pc
/usr/lib32/pkgconfig/flac.pc

%files doc
%defattr(-,root,root,-)
%doc /usr/share/doc/flac/*
%doc /usr/share/man/man1/*

%files lib
%defattr(-,root,root,-)
/usr/lib64/libFLAC++.so.6
/usr/lib64/libFLAC++.so.6.3.0
/usr/lib64/libFLAC.so.8
/usr/lib64/libFLAC.so.8.3.0

%files lib32
%defattr(-,root,root,-)
/usr/lib32/libFLAC++.so.6
/usr/lib32/libFLAC++.so.6.3.0
/usr/lib32/libFLAC.so.8
/usr/lib32/libFLAC.so.8.3.0
