#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : flac
Version  : 1.3.2
Release  : 17
URL      : http://downloads.xiph.org/releases/flac/flac-1.3.2.tar.xz
Source0  : http://downloads.xiph.org/releases/flac/flac-1.3.2.tar.xz
Summary  : Free Lossless Audio Codec Library
Group    : Development/Tools
License  : BSD-3-Clause GFDL-1.2 GPL-2.0 LGPL-2.1
Requires: flac-bin
Requires: flac-lib
Requires: flac-data
Requires: flac-doc
BuildRequires : doxygen
BuildRequires : gcc-dev32
BuildRequires : gcc-libgcc32
BuildRequires : gcc-libstdc++32
BuildRequires : glibc-dev32
BuildRequires : glibc-libc32
BuildRequires : libogg-dev32
BuildRequires : nasm-bin

%description
/* FLAC - Free Lossless Audio Codec
*
* This file is part the FLAC project.  FLAC is comprised of several
* components distributed under different licenses.  The codec libraries
* are distributed under Xiph.Org's BSD-like license (see the file
* COPYING.Xiph in this distribution).  All other programs, libraries, and
* plugins are distributed under the LGPL or GPL (see COPYING.LGPL and
* COPYING.GPL).  The documentation is distributed under the Gnu FDL (see
* COPYING.FDL).  Each file in the FLAC distribution contains at the top the
* terms under which it may be distributed.
*
* Since this particular file is relevant to all components of FLAC,
* it may be distributed under the Xiph.Org license, which is the least
* restrictive of those mentioned above.  See the file COPYING.Xiph in this
* distribution.
*/

%package bin
Summary: bin components for the flac package.
Group: Binaries
Requires: flac-data

%description bin
bin components for the flac package.


%package data
Summary: data components for the flac package.
Group: Data

%description data
data components for the flac package.


%package dev
Summary: dev components for the flac package.
Group: Development
Requires: flac-lib
Requires: flac-bin
Requires: flac-data
Provides: flac-devel

%description dev
dev components for the flac package.


%package dev32
Summary: dev32 components for the flac package.
Group: Default
Requires: flac-lib32
Requires: flac-bin
Requires: flac-data
Requires: flac-dev

%description dev32
dev32 components for the flac package.


%package doc
Summary: doc components for the flac package.
Group: Documentation

%description doc
doc components for the flac package.


%package lib
Summary: lib components for the flac package.
Group: Libraries
Requires: flac-data

%description lib
lib components for the flac package.


%package lib32
Summary: lib32 components for the flac package.
Group: Default
Requires: flac-data

%description lib32
lib32 components for the flac package.


%prep
%setup -q -n flac-1.3.2
pushd ..
cp -a flac-1.3.2 build32
popd
pushd ..
cp -a flac-1.3.2 buildavx2
popd
pushd ..
cp -a flac-1.3.2 buildavx512
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1514736468
export CFLAGS="$CFLAGS -O3 -falign-functions=32 -ffast-math -fno-math-errno -fno-semantic-interposition -fno-trapping-math -ftree-loop-vectorize "
export FCFLAGS="$CFLAGS -O3 -falign-functions=32 -ffast-math -fno-math-errno -fno-semantic-interposition -fno-trapping-math -ftree-loop-vectorize "
export FFLAGS="$CFLAGS -O3 -falign-functions=32 -ffast-math -fno-math-errno -fno-semantic-interposition -fno-trapping-math -ftree-loop-vectorize "
export CXXFLAGS="$CXXFLAGS -O3 -falign-functions=32 -ffast-math -fno-math-errno -fno-semantic-interposition -fno-trapping-math -ftree-loop-vectorize "
%configure --disable-static
make  %{?_smp_mflags}

pushd ../build32/
export PKG_CONFIG_PATH="/usr/lib32/pkgconfig"
export CFLAGS="$CFLAGS -m32"
export CXXFLAGS="$CXXFLAGS -m32"
export LDFLAGS="$LDFLAGS -m32"
%configure --disable-static    --libdir=/usr/lib32 --build=i686-generic-linux-gnu --host=i686-generic-linux-gnu --target=i686-clr-linux-gnu
make  %{?_smp_mflags}
popd
pushd ../buildavx2/
export CFLAGS="$CFLAGS -m64 -march=haswell"
export CXXFLAGS="$CXXFLAGS -m64 -march=haswell"
export LDFLAGS="$LDFLAGS -m64 -march=haswell"
%configure --disable-static    --libdir=/usr/lib64/haswell --bindir=/usr/bin/haswell
make  %{?_smp_mflags}
popd
pushd ../buildavx512/
export CFLAGS="$CFLAGS -m64 -march=skylake-avx512"
export CXXFLAGS="$CXXFLAGS -m64 -march=skylake-avx512"
export LDFLAGS="$LDFLAGS -m64 -march=skylake-avx512"
%configure --disable-static    --libdir=/usr/lib64/haswell/avx512_1 --bindir=/usr/bin/haswell/avx512_1
make  %{?_smp_mflags}
popd
%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make VERBOSE=1 V=1 %{?_smp_mflags} check || :

%install
export SOURCE_DATE_EPOCH=1514736468
rm -rf %{buildroot}
pushd ../build32/
%make_install32
if [ -d  %{buildroot}/usr/lib32/pkgconfig ]
then
pushd %{buildroot}/usr/lib32/pkgconfig
for i in *.pc ; do ln -s $i 32$i ; done
popd
fi
popd
pushd ../buildavx2/
%make_install
popd
pushd ../buildavx512/
%make_install
popd
%make_install

%files
%defattr(-,root,root,-)
/usr/lib64/haswell/avx512_1/pkgconfig/flac++.pc
/usr/lib64/haswell/avx512_1/pkgconfig/flac.pc
/usr/lib64/haswell/pkgconfig/flac++.pc
/usr/lib64/haswell/pkgconfig/flac.pc

%files bin
%defattr(-,root,root,-)
/usr/bin/flac
/usr/bin/haswell/avx512_1/flac
/usr/bin/haswell/avx512_1/metaflac
/usr/bin/haswell/flac
/usr/bin/haswell/metaflac
/usr/bin/metaflac

%files data
%defattr(-,root,root,-)
/usr/share/doc/flac-1.3.2/FLAC.tag
/usr/share/doc/flac-1.3.2/html/api/_09_2all_8h_source.html
/usr/share/doc/flac-1.3.2/html/api/_09_2export_8h.html
/usr/share/doc/flac-1.3.2/html/api/_09_2export_8h_source.html
/usr/share/doc/flac-1.3.2/html/api/_09_2metadata_8h.html
/usr/share/doc/flac-1.3.2/html/api/_09_2metadata_8h_source.html
/usr/share/doc/flac-1.3.2/html/api/all_8h_source.html
/usr/share/doc/flac-1.3.2/html/api/annotated.html
/usr/share/doc/flac-1.3.2/html/api/assert_8h_source.html
/usr/share/doc/flac-1.3.2/html/api/bc_s.png
/usr/share/doc/flac-1.3.2/html/api/bdwn.png
/usr/share/doc/flac-1.3.2/html/api/callback_8h.html
/usr/share/doc/flac-1.3.2/html/api/callback_8h_source.html
/usr/share/doc/flac-1.3.2/html/api/classFLAC_1_1Decoder_1_1File-members.html
/usr/share/doc/flac-1.3.2/html/api/classFLAC_1_1Decoder_1_1File.html
/usr/share/doc/flac-1.3.2/html/api/classFLAC_1_1Decoder_1_1File.png
/usr/share/doc/flac-1.3.2/html/api/classFLAC_1_1Decoder_1_1Stream-members.html
/usr/share/doc/flac-1.3.2/html/api/classFLAC_1_1Decoder_1_1Stream.html
/usr/share/doc/flac-1.3.2/html/api/classFLAC_1_1Decoder_1_1Stream.png
/usr/share/doc/flac-1.3.2/html/api/classFLAC_1_1Decoder_1_1Stream_1_1State-members.html
/usr/share/doc/flac-1.3.2/html/api/classFLAC_1_1Decoder_1_1Stream_1_1State.html
/usr/share/doc/flac-1.3.2/html/api/classFLAC_1_1Encoder_1_1File-members.html
/usr/share/doc/flac-1.3.2/html/api/classFLAC_1_1Encoder_1_1File.html
/usr/share/doc/flac-1.3.2/html/api/classFLAC_1_1Encoder_1_1File.png
/usr/share/doc/flac-1.3.2/html/api/classFLAC_1_1Encoder_1_1Stream-members.html
/usr/share/doc/flac-1.3.2/html/api/classFLAC_1_1Encoder_1_1Stream.html
/usr/share/doc/flac-1.3.2/html/api/classFLAC_1_1Encoder_1_1Stream.png
/usr/share/doc/flac-1.3.2/html/api/classFLAC_1_1Encoder_1_1Stream_1_1State-members.html
/usr/share/doc/flac-1.3.2/html/api/classFLAC_1_1Encoder_1_1Stream_1_1State.html
/usr/share/doc/flac-1.3.2/html/api/classFLAC_1_1Metadata_1_1Application-members.html
/usr/share/doc/flac-1.3.2/html/api/classFLAC_1_1Metadata_1_1Application.html
/usr/share/doc/flac-1.3.2/html/api/classFLAC_1_1Metadata_1_1Application.png
/usr/share/doc/flac-1.3.2/html/api/classFLAC_1_1Metadata_1_1Chain-members.html
/usr/share/doc/flac-1.3.2/html/api/classFLAC_1_1Metadata_1_1Chain.html
/usr/share/doc/flac-1.3.2/html/api/classFLAC_1_1Metadata_1_1Chain_1_1Status-members.html
/usr/share/doc/flac-1.3.2/html/api/classFLAC_1_1Metadata_1_1Chain_1_1Status.html
/usr/share/doc/flac-1.3.2/html/api/classFLAC_1_1Metadata_1_1CueSheet-members.html
/usr/share/doc/flac-1.3.2/html/api/classFLAC_1_1Metadata_1_1CueSheet.html
/usr/share/doc/flac-1.3.2/html/api/classFLAC_1_1Metadata_1_1CueSheet.png
/usr/share/doc/flac-1.3.2/html/api/classFLAC_1_1Metadata_1_1CueSheet_1_1Track-members.html
/usr/share/doc/flac-1.3.2/html/api/classFLAC_1_1Metadata_1_1CueSheet_1_1Track.html
/usr/share/doc/flac-1.3.2/html/api/classFLAC_1_1Metadata_1_1Iterator-members.html
/usr/share/doc/flac-1.3.2/html/api/classFLAC_1_1Metadata_1_1Iterator.html
/usr/share/doc/flac-1.3.2/html/api/classFLAC_1_1Metadata_1_1Padding-members.html
/usr/share/doc/flac-1.3.2/html/api/classFLAC_1_1Metadata_1_1Padding.html
/usr/share/doc/flac-1.3.2/html/api/classFLAC_1_1Metadata_1_1Padding.png
/usr/share/doc/flac-1.3.2/html/api/classFLAC_1_1Metadata_1_1Picture-members.html
/usr/share/doc/flac-1.3.2/html/api/classFLAC_1_1Metadata_1_1Picture.html
/usr/share/doc/flac-1.3.2/html/api/classFLAC_1_1Metadata_1_1Picture.png
/usr/share/doc/flac-1.3.2/html/api/classFLAC_1_1Metadata_1_1Prototype-members.html
/usr/share/doc/flac-1.3.2/html/api/classFLAC_1_1Metadata_1_1Prototype.html
/usr/share/doc/flac-1.3.2/html/api/classFLAC_1_1Metadata_1_1Prototype.png
/usr/share/doc/flac-1.3.2/html/api/classFLAC_1_1Metadata_1_1SeekTable-members.html
/usr/share/doc/flac-1.3.2/html/api/classFLAC_1_1Metadata_1_1SeekTable.html
/usr/share/doc/flac-1.3.2/html/api/classFLAC_1_1Metadata_1_1SeekTable.png
/usr/share/doc/flac-1.3.2/html/api/classFLAC_1_1Metadata_1_1SimpleIterator-members.html
/usr/share/doc/flac-1.3.2/html/api/classFLAC_1_1Metadata_1_1SimpleIterator.html
/usr/share/doc/flac-1.3.2/html/api/classFLAC_1_1Metadata_1_1SimpleIterator_1_1Status-members.html
/usr/share/doc/flac-1.3.2/html/api/classFLAC_1_1Metadata_1_1SimpleIterator_1_1Status.html
/usr/share/doc/flac-1.3.2/html/api/classFLAC_1_1Metadata_1_1StreamInfo-members.html
/usr/share/doc/flac-1.3.2/html/api/classFLAC_1_1Metadata_1_1StreamInfo.html
/usr/share/doc/flac-1.3.2/html/api/classFLAC_1_1Metadata_1_1StreamInfo.png
/usr/share/doc/flac-1.3.2/html/api/classFLAC_1_1Metadata_1_1Unknown-members.html
/usr/share/doc/flac-1.3.2/html/api/classFLAC_1_1Metadata_1_1Unknown.html
/usr/share/doc/flac-1.3.2/html/api/classFLAC_1_1Metadata_1_1Unknown.png
/usr/share/doc/flac-1.3.2/html/api/classFLAC_1_1Metadata_1_1VorbisComment-members.html
/usr/share/doc/flac-1.3.2/html/api/classFLAC_1_1Metadata_1_1VorbisComment.html
/usr/share/doc/flac-1.3.2/html/api/classFLAC_1_1Metadata_1_1VorbisComment.png
/usr/share/doc/flac-1.3.2/html/api/classFLAC_1_1Metadata_1_1VorbisComment_1_1Entry-members.html
/usr/share/doc/flac-1.3.2/html/api/classFLAC_1_1Metadata_1_1VorbisComment_1_1Entry.html
/usr/share/doc/flac-1.3.2/html/api/classes.html
/usr/share/doc/flac-1.3.2/html/api/closed.png
/usr/share/doc/flac-1.3.2/html/api/decoder_8h.html
/usr/share/doc/flac-1.3.2/html/api/decoder_8h_source.html
/usr/share/doc/flac-1.3.2/html/api/dir_1982b5890de532b4beef7221dae776e2.html
/usr/share/doc/flac-1.3.2/html/api/dir_527642952c2881b3e5b36abb4a29ebef.html
/usr/share/doc/flac-1.3.2/html/api/dir_d44c64559bbebec7f509842c48db8b23.html
/usr/share/doc/flac-1.3.2/html/api/doc.png
/usr/share/doc/flac-1.3.2/html/api/doxygen.css
/usr/share/doc/flac-1.3.2/html/api/doxygen.png
/usr/share/doc/flac-1.3.2/html/api/dynsections.js
/usr/share/doc/flac-1.3.2/html/api/encoder_8h.html
/usr/share/doc/flac-1.3.2/html/api/encoder_8h_source.html
/usr/share/doc/flac-1.3.2/html/api/export_8h.html
/usr/share/doc/flac-1.3.2/html/api/export_8h_source.html
/usr/share/doc/flac-1.3.2/html/api/files.html
/usr/share/doc/flac-1.3.2/html/api/folderclosed.png
/usr/share/doc/flac-1.3.2/html/api/folderopen.png
/usr/share/doc/flac-1.3.2/html/api/format_8h.html
/usr/share/doc/flac-1.3.2/html/api/format_8h_source.html
/usr/share/doc/flac-1.3.2/html/api/functions.html
/usr/share/doc/flac-1.3.2/html/api/functions_0x7e.html
/usr/share/doc/flac-1.3.2/html/api/functions_b.html
/usr/share/doc/flac-1.3.2/html/api/functions_c.html
/usr/share/doc/flac-1.3.2/html/api/functions_d.html
/usr/share/doc/flac-1.3.2/html/api/functions_e.html
/usr/share/doc/flac-1.3.2/html/api/functions_f.html
/usr/share/doc/flac-1.3.2/html/api/functions_func.html
/usr/share/doc/flac-1.3.2/html/api/functions_func_0x7e.html
/usr/share/doc/flac-1.3.2/html/api/functions_func_c.html
/usr/share/doc/flac-1.3.2/html/api/functions_func_d.html
/usr/share/doc/flac-1.3.2/html/api/functions_func_e.html
/usr/share/doc/flac-1.3.2/html/api/functions_func_f.html
/usr/share/doc/flac-1.3.2/html/api/functions_func_g.html
/usr/share/doc/flac-1.3.2/html/api/functions_func_i.html
/usr/share/doc/flac-1.3.2/html/api/functions_func_l.html
/usr/share/doc/flac-1.3.2/html/api/functions_func_m.html
/usr/share/doc/flac-1.3.2/html/api/functions_func_n.html
/usr/share/doc/flac-1.3.2/html/api/functions_func_o.html
/usr/share/doc/flac-1.3.2/html/api/functions_func_p.html
/usr/share/doc/flac-1.3.2/html/api/functions_func_r.html
/usr/share/doc/flac-1.3.2/html/api/functions_func_s.html
/usr/share/doc/flac-1.3.2/html/api/functions_func_t.html
/usr/share/doc/flac-1.3.2/html/api/functions_func_u.html
/usr/share/doc/flac-1.3.2/html/api/functions_func_v.html
/usr/share/doc/flac-1.3.2/html/api/functions_func_w.html
/usr/share/doc/flac-1.3.2/html/api/functions_g.html
/usr/share/doc/flac-1.3.2/html/api/functions_h.html
/usr/share/doc/flac-1.3.2/html/api/functions_i.html
/usr/share/doc/flac-1.3.2/html/api/functions_l.html
/usr/share/doc/flac-1.3.2/html/api/functions_m.html
/usr/share/doc/flac-1.3.2/html/api/functions_n.html
/usr/share/doc/flac-1.3.2/html/api/functions_o.html
/usr/share/doc/flac-1.3.2/html/api/functions_p.html
/usr/share/doc/flac-1.3.2/html/api/functions_q.html
/usr/share/doc/flac-1.3.2/html/api/functions_r.html
/usr/share/doc/flac-1.3.2/html/api/functions_s.html
/usr/share/doc/flac-1.3.2/html/api/functions_t.html
/usr/share/doc/flac-1.3.2/html/api/functions_u.html
/usr/share/doc/flac-1.3.2/html/api/functions_v.html
/usr/share/doc/flac-1.3.2/html/api/functions_vars.html
/usr/share/doc/flac-1.3.2/html/api/functions_w.html
/usr/share/doc/flac-1.3.2/html/api/globals.html
/usr/share/doc/flac-1.3.2/html/api/globals_defs.html
/usr/share/doc/flac-1.3.2/html/api/globals_enum.html
/usr/share/doc/flac-1.3.2/html/api/globals_eval.html
/usr/share/doc/flac-1.3.2/html/api/globals_func.html
/usr/share/doc/flac-1.3.2/html/api/globals_type.html
/usr/share/doc/flac-1.3.2/html/api/globals_vars.html
/usr/share/doc/flac-1.3.2/html/api/group__flac.html
/usr/share/doc/flac-1.3.2/html/api/group__flac__callbacks.html
/usr/share/doc/flac-1.3.2/html/api/group__flac__decoder.html
/usr/share/doc/flac-1.3.2/html/api/group__flac__encoder.html
/usr/share/doc/flac-1.3.2/html/api/group__flac__export.html
/usr/share/doc/flac-1.3.2/html/api/group__flac__format.html
/usr/share/doc/flac-1.3.2/html/api/group__flac__metadata.html
/usr/share/doc/flac-1.3.2/html/api/group__flac__metadata__level0.html
/usr/share/doc/flac-1.3.2/html/api/group__flac__metadata__level1.html
/usr/share/doc/flac-1.3.2/html/api/group__flac__metadata__level2.html
/usr/share/doc/flac-1.3.2/html/api/group__flac__metadata__object.html
/usr/share/doc/flac-1.3.2/html/api/group__flac__stream__decoder.html
/usr/share/doc/flac-1.3.2/html/api/group__flac__stream__encoder.html
/usr/share/doc/flac-1.3.2/html/api/group__flacpp.html
/usr/share/doc/flac-1.3.2/html/api/group__flacpp__decoder.html
/usr/share/doc/flac-1.3.2/html/api/group__flacpp__encoder.html
/usr/share/doc/flac-1.3.2/html/api/group__flacpp__export.html
/usr/share/doc/flac-1.3.2/html/api/group__flacpp__metadata.html
/usr/share/doc/flac-1.3.2/html/api/group__flacpp__metadata__level0.html
/usr/share/doc/flac-1.3.2/html/api/group__flacpp__metadata__level1.html
/usr/share/doc/flac-1.3.2/html/api/group__flacpp__metadata__level2.html
/usr/share/doc/flac-1.3.2/html/api/group__flacpp__metadata__object.html
/usr/share/doc/flac-1.3.2/html/api/group__porting.html
/usr/share/doc/flac-1.3.2/html/api/group__porting__1__1__2__to__1__1__3.html
/usr/share/doc/flac-1.3.2/html/api/group__porting__1__1__3__to__1__1__4.html
/usr/share/doc/flac-1.3.2/html/api/group__porting__1__1__4__to__1__2__0.html
/usr/share/doc/flac-1.3.2/html/api/hierarchy.html
/usr/share/doc/flac-1.3.2/html/api/index.html
/usr/share/doc/flac-1.3.2/html/api/jquery.js
/usr/share/doc/flac-1.3.2/html/api/menu.js
/usr/share/doc/flac-1.3.2/html/api/menudata.js
/usr/share/doc/flac-1.3.2/html/api/metadata_8h.html
/usr/share/doc/flac-1.3.2/html/api/metadata_8h_source.html
/usr/share/doc/flac-1.3.2/html/api/modules.html
/usr/share/doc/flac-1.3.2/html/api/nav_f.png
/usr/share/doc/flac-1.3.2/html/api/nav_g.png
/usr/share/doc/flac-1.3.2/html/api/nav_h.png
/usr/share/doc/flac-1.3.2/html/api/open.png
/usr/share/doc/flac-1.3.2/html/api/ordinals_8h_source.html
/usr/share/doc/flac-1.3.2/html/api/splitbar.png
/usr/share/doc/flac-1.3.2/html/api/stream__decoder_8h.html
/usr/share/doc/flac-1.3.2/html/api/stream__decoder_8h_source.html
/usr/share/doc/flac-1.3.2/html/api/stream__encoder_8h.html
/usr/share/doc/flac-1.3.2/html/api/stream__encoder_8h_source.html
/usr/share/doc/flac-1.3.2/html/api/structFLAC____EntropyCodingMethod-members.html
/usr/share/doc/flac-1.3.2/html/api/structFLAC____EntropyCodingMethod.html
/usr/share/doc/flac-1.3.2/html/api/structFLAC____EntropyCodingMethod__PartitionedRice-members.html
/usr/share/doc/flac-1.3.2/html/api/structFLAC____EntropyCodingMethod__PartitionedRice.html
/usr/share/doc/flac-1.3.2/html/api/structFLAC____EntropyCodingMethod__PartitionedRiceContents-members.html
/usr/share/doc/flac-1.3.2/html/api/structFLAC____EntropyCodingMethod__PartitionedRiceContents.html
/usr/share/doc/flac-1.3.2/html/api/structFLAC____Frame-members.html
/usr/share/doc/flac-1.3.2/html/api/structFLAC____Frame.html
/usr/share/doc/flac-1.3.2/html/api/structFLAC____FrameFooter-members.html
/usr/share/doc/flac-1.3.2/html/api/structFLAC____FrameFooter.html
/usr/share/doc/flac-1.3.2/html/api/structFLAC____FrameHeader-members.html
/usr/share/doc/flac-1.3.2/html/api/structFLAC____FrameHeader.html
/usr/share/doc/flac-1.3.2/html/api/structFLAC____IOCallbacks-members.html
/usr/share/doc/flac-1.3.2/html/api/structFLAC____IOCallbacks.html
/usr/share/doc/flac-1.3.2/html/api/structFLAC____StreamDecoder-members.html
/usr/share/doc/flac-1.3.2/html/api/structFLAC____StreamDecoder.html
/usr/share/doc/flac-1.3.2/html/api/structFLAC____StreamEncoder-members.html
/usr/share/doc/flac-1.3.2/html/api/structFLAC____StreamEncoder.html
/usr/share/doc/flac-1.3.2/html/api/structFLAC____StreamMetadata-members.html
/usr/share/doc/flac-1.3.2/html/api/structFLAC____StreamMetadata.html
/usr/share/doc/flac-1.3.2/html/api/structFLAC____StreamMetadata__Application-members.html
/usr/share/doc/flac-1.3.2/html/api/structFLAC____StreamMetadata__Application.html
/usr/share/doc/flac-1.3.2/html/api/structFLAC____StreamMetadata__CueSheet-members.html
/usr/share/doc/flac-1.3.2/html/api/structFLAC____StreamMetadata__CueSheet.html
/usr/share/doc/flac-1.3.2/html/api/structFLAC____StreamMetadata__CueSheet__Index-members.html
/usr/share/doc/flac-1.3.2/html/api/structFLAC____StreamMetadata__CueSheet__Index.html
/usr/share/doc/flac-1.3.2/html/api/structFLAC____StreamMetadata__CueSheet__Track-members.html
/usr/share/doc/flac-1.3.2/html/api/structFLAC____StreamMetadata__CueSheet__Track.html
/usr/share/doc/flac-1.3.2/html/api/structFLAC____StreamMetadata__Padding-members.html
/usr/share/doc/flac-1.3.2/html/api/structFLAC____StreamMetadata__Padding.html
/usr/share/doc/flac-1.3.2/html/api/structFLAC____StreamMetadata__Picture-members.html
/usr/share/doc/flac-1.3.2/html/api/structFLAC____StreamMetadata__Picture.html
/usr/share/doc/flac-1.3.2/html/api/structFLAC____StreamMetadata__SeekPoint-members.html
/usr/share/doc/flac-1.3.2/html/api/structFLAC____StreamMetadata__SeekPoint.html
/usr/share/doc/flac-1.3.2/html/api/structFLAC____StreamMetadata__SeekTable-members.html
/usr/share/doc/flac-1.3.2/html/api/structFLAC____StreamMetadata__SeekTable.html
/usr/share/doc/flac-1.3.2/html/api/structFLAC____StreamMetadata__StreamInfo-members.html
/usr/share/doc/flac-1.3.2/html/api/structFLAC____StreamMetadata__StreamInfo.html
/usr/share/doc/flac-1.3.2/html/api/structFLAC____StreamMetadata__Unknown-members.html
/usr/share/doc/flac-1.3.2/html/api/structFLAC____StreamMetadata__Unknown.html
/usr/share/doc/flac-1.3.2/html/api/structFLAC____StreamMetadata__VorbisComment-members.html
/usr/share/doc/flac-1.3.2/html/api/structFLAC____StreamMetadata__VorbisComment.html
/usr/share/doc/flac-1.3.2/html/api/structFLAC____StreamMetadata__VorbisComment__Entry-members.html
/usr/share/doc/flac-1.3.2/html/api/structFLAC____StreamMetadata__VorbisComment__Entry.html
/usr/share/doc/flac-1.3.2/html/api/structFLAC____Subframe-members.html
/usr/share/doc/flac-1.3.2/html/api/structFLAC____Subframe.html
/usr/share/doc/flac-1.3.2/html/api/structFLAC____Subframe__Constant-members.html
/usr/share/doc/flac-1.3.2/html/api/structFLAC____Subframe__Constant.html
/usr/share/doc/flac-1.3.2/html/api/structFLAC____Subframe__Fixed-members.html
/usr/share/doc/flac-1.3.2/html/api/structFLAC____Subframe__Fixed.html
/usr/share/doc/flac-1.3.2/html/api/structFLAC____Subframe__LPC-members.html
/usr/share/doc/flac-1.3.2/html/api/structFLAC____Subframe__LPC.html
/usr/share/doc/flac-1.3.2/html/api/structFLAC____Subframe__Verbatim-members.html
/usr/share/doc/flac-1.3.2/html/api/structFLAC____Subframe__Verbatim.html
/usr/share/doc/flac-1.3.2/html/api/sync_off.png
/usr/share/doc/flac-1.3.2/html/api/sync_on.png
/usr/share/doc/flac-1.3.2/html/api/tab_a.png
/usr/share/doc/flac-1.3.2/html/api/tab_b.png
/usr/share/doc/flac-1.3.2/html/api/tab_h.png
/usr/share/doc/flac-1.3.2/html/api/tab_s.png
/usr/share/doc/flac-1.3.2/html/api/tabs.css
/usr/share/doc/flac-1.3.2/html/changelog.html
/usr/share/doc/flac-1.3.2/html/developers.html
/usr/share/doc/flac-1.3.2/html/documentation.html
/usr/share/doc/flac-1.3.2/html/documentation_bugs.html
/usr/share/doc/flac-1.3.2/html/documentation_example_code.html
/usr/share/doc/flac-1.3.2/html/documentation_format_overview.html
/usr/share/doc/flac-1.3.2/html/documentation_tools.html
/usr/share/doc/flac-1.3.2/html/documentation_tools_flac.html
/usr/share/doc/flac-1.3.2/html/documentation_tools_metaflac.html
/usr/share/doc/flac-1.3.2/html/faq.html
/usr/share/doc/flac-1.3.2/html/favicon.ico
/usr/share/doc/flac-1.3.2/html/features.html
/usr/share/doc/flac-1.3.2/html/flac.css
/usr/share/doc/flac-1.3.2/html/format.html
/usr/share/doc/flac-1.3.2/html/id.html
/usr/share/doc/flac-1.3.2/html/images/logo.svg
/usr/share/doc/flac-1.3.2/html/images/logo130.gif
/usr/share/doc/flac-1.3.2/html/index.html
/usr/share/doc/flac-1.3.2/html/license.html
/usr/share/doc/flac-1.3.2/html/ogg_mapping.html

%files dev
%defattr(-,root,root,-)
/usr/include/FLAC++/all.h
/usr/include/FLAC++/decoder.h
/usr/include/FLAC++/encoder.h
/usr/include/FLAC++/export.h
/usr/include/FLAC++/metadata.h
/usr/include/FLAC/all.h
/usr/include/FLAC/assert.h
/usr/include/FLAC/callback.h
/usr/include/FLAC/export.h
/usr/include/FLAC/format.h
/usr/include/FLAC/metadata.h
/usr/include/FLAC/ordinals.h
/usr/include/FLAC/stream_decoder.h
/usr/include/FLAC/stream_encoder.h
/usr/lib64/haswell/libFLAC++.so
/usr/lib64/haswell/libFLAC.so
/usr/lib64/libFLAC++.so
/usr/lib64/libFLAC.so
/usr/lib64/pkgconfig/flac++.pc
/usr/lib64/pkgconfig/flac.pc
/usr/share/aclocal/*.m4

%files dev32
%defattr(-,root,root,-)
/usr/lib32/libFLAC++.so
/usr/lib32/libFLAC.so
/usr/lib32/pkgconfig/32flac++.pc
/usr/lib32/pkgconfig/32flac.pc
/usr/lib32/pkgconfig/flac++.pc
/usr/lib32/pkgconfig/flac.pc

%files doc
%defattr(-,root,root,-)
%doc /usr/share/doc/flac/*
%doc /usr/share/man/man1/*

%files lib
%defattr(-,root,root,-)
/usr/lib64/haswell/avx512_1/libFLAC++.so
/usr/lib64/haswell/avx512_1/libFLAC++.so.6
/usr/lib64/haswell/avx512_1/libFLAC++.so.6.3.0
/usr/lib64/haswell/avx512_1/libFLAC.so
/usr/lib64/haswell/avx512_1/libFLAC.so.8
/usr/lib64/haswell/avx512_1/libFLAC.so.8.3.0
/usr/lib64/haswell/libFLAC++.so.6
/usr/lib64/haswell/libFLAC++.so.6.3.0
/usr/lib64/haswell/libFLAC.so.8
/usr/lib64/haswell/libFLAC.so.8.3.0
/usr/lib64/libFLAC++.so.6
/usr/lib64/libFLAC++.so.6.3.0
/usr/lib64/libFLAC.so.8
/usr/lib64/libFLAC.so.8.3.0

%files lib32
%defattr(-,root,root,-)
/usr/lib32/libFLAC++.so.6
/usr/lib32/libFLAC++.so.6.3.0
/usr/lib32/libFLAC.so.8
/usr/lib32/libFLAC.so.8.3.0
